/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import Gallery from '../components/Gallery';
import HomeMain from '../components/HomeMain';
import Navbar from '../components/Navbar';
import Popular from '../components/Popular';
import Speciality from '../components/Speciality';
import Steps from '../components/Steps';
import { AiOutlineUp } from 'react-icons/ai';
import { useEffect } from 'react';
import Footer from '../components/Footer';

export default function Home() {

  const handleScroll = () => { }

  useEffect(() => {
    window.onscroll = () => {
      if (window.scrollY > 60) {
        document.querySelector('#scroll-top').classList.add('active');
      } else {
        document.querySelector('#scroll-top').classList.remove('active');
      }
    }

    function loader() {
      document.querySelector('.loader-container').classList.add('fade-out');
    }
    function fadeOut() {
      setInterval(loader, 3000);
    }

    window.onload = fadeOut();
  }, []);

  return (
    <div>
      <Head>
        <title>Food App Next JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HomeMain />
      <Speciality />
      <Popular />
      <Steps />
      <Gallery />
      <Footer/>

      <a href="#home" id="scroll-top">
        <AiOutlineUp />
      </a>

      <div className="loader-container">
        <img src="images/loader.gif" alt="" />
      </div>
    </div>
  )
}
